server:
  port: 3303

spring:
  application:
    name: cisdi-info-ms-cms_sample
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weibo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
        properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5InnoDBDialect #指定数据库引擎
mybatis:
    mapper-locations:
     # - classpath*:/com/cisdi/info/sqlMapper/**/*.xml #mybaits mapperxml文件路径，使用了cms后不要修改或者删除
      - classpath*:/com/dao/mapper/*.xml #mybaits mapperxml文件路径
    type-aliases-package: com.weibo.entity
    configuration:
        map-underscore-to-camel-case: true
